# Generated by Django 4.2.2 on 2024-04-24 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('preferred_contact_time', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('num_guests', models.IntegerField()),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('gathering', 'Large Gathering'), ('birthday', 'Birthday'), ('corp-event', 'Corporate Event'), ('popup', 'Popup')], max_length=20)),
                ('event_date', models.DateField()),
                ('pickup_delivery', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=10)),
                ('pickup_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=200, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
