# Generated by Django 4.2.2 on 2024-04-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryform',
            name='company_name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='delivery_address',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='delivery_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='event_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('gathering', 'Large Gathering'), ('birthday', 'Birthday'), ('corp-event', 'Corporate Event'), ('popup', 'Popup')], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='first_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='last_name',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='num_guests',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='phone_number',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='pickup_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='pickup_delivery',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='pickup_name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='preferred_contact_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='special_requests',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
