# Generated by Django 5.0.3 on 2024-05-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_remove_inquiryform_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiryform',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='inquiryform',
            name='time_sent',
        ),
    ]
