# Generated by Django 5.0.3 on 2024-05-14 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0006_inquiryform_date_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryform',
            name='time_sent',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
