# Generated by Django 5.0.3 on 2024-05-14 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0008_remove_inquiryform_date_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryform',
            name='date_time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inquiryform',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiryform',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
