# Generated by Django 5.0.3 on 2024-07-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0009_inquiryform_date_time_sent_inquiryform_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiryform',
            name='subject',
            field=models.CharField(default='subject', max_length=10),
            preserve_default=False,
        ),
    ]
