# Generated by Django 4.2.2 on 2024-04-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_price_product_dozen_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_title',
            field=models.CharField(help_text='Title of the product', max_length=250),
        ),
    ]
