# Generated by Django 4.2.2 on 2024-04-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique slug for URL', unique=True)),
                ('name', models.CharField(help_text='Name of the category', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(help_text='Title of the product', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the product', max_digits=4)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the product')),
                ('slug', models.SlugField(help_text='Unique slug for URL', unique=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
