# Generated by Django 4.2.2 on 2024-04-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='dozen_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per dozen', max_digits=4),
        ),
        migrations.AddField(
            model_name='product',
            name='half_dozen_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per half dozen', max_digits=4),
        ),
    ]
