# Generated by Django 4.2.2 on 2024-04-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                help_text='Unique slug for URL', unique=True),
        ),
    ]
