# Generated by Django 4.2.2 on 2024-05-16 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
